 - name: Настройка Java JDK
 использует: actions/setup-java@v5.0.0
 с параметрами:
 # Версия Java для настройки. Принимает полную или сокращенную версию Java. Примеры поддерживаемого синтаксиса см. в файле README
 java-version: # необязательно
 # Путь к файлу `.java-version`. Примеры поддерживаемого синтаксиса см. в файле README
 java-version-file: # необязательно
 # Дистрибутив Java. Список поддерживаемых дистрибутивов см. в файле README
 distribution: 
 # Тип пакета (jdk, jre, jdk+fx, jre+fx)
 java-package: # необязательно, по умолчанию jdk
 # Архитектура пакета (по умолчанию соответствует архитектуре средства запуска действий)
 architecture: # необязательно
 # Путь к сжатому JDK
 jdkFile: # необязательно
 # Установите этот параметр, если хотите, чтобы действие проверяло наличие последней доступной версии, соответствующей спецификации версии
 check-latest: # необязательно
 # Идентификатор репозитория distributionManagement в файле pom.xml.  По умолчанию используется `github`
 server-id: # необязательно, по умолчанию используется github
 # Имя переменной среды для имени пользователя для аутентификации в репозитории Apache Maven.  По умолчанию используется $GITHUB_ACTOR
 server-username: # необязательно, по умолчанию используется GITHUB_ACTOR
 # Имя переменной среды для пароля или токена для аутентификации в репозитории Apache Maven. По умолчанию используется $GITHUB_TOKEN
 server-password: # необязательно, по умолчанию используется GITHUB_TOKEN
 # Путь, по которому будет записан файл settings.xml. По умолчанию используется ~/.m2.
 settings-path: # необязательно
 # Перезаписать файл settings.xml, если он существует. По умолчанию используется "true".
 overwrite-settings: # необязательно, по умолчанию используется true
 # Закрытый ключ GPG для импорта. По умолчанию — пустая строка.
 gpg-private-key: # необязательно
 # Имя переменной среды для кодовой фразы закрытого ключа GPG. По умолчанию — $GPG_PASSPHRASE.
 gpg-passphrase: # необязательно
 # Имя платформы сборки для кэширования зависимостей. Это может быть "maven", "gradle" или "sbt".
 cache: # необязательно
 # Путь к файлу зависимостей: pom.xml, build.gradle, build.sbt и т. д. Этот параметр можно использовать с параметром `cache`. Если этот параметр не указан, действие будет искать файл зависимостей во всём репозитории. Этот параметр поддерживает подстановочные знаки и список имён файлов для кэширования нескольких зависимостей.
 cache-dependency-path: # необязательно
 # Обходной путь для передачи статуса задания на этапе публикации задания. Эта переменная не предназначена для ручной настройки
 job-status: # необязательно, по умолчанию ${{ job.status }}
 # Токен, используемый для аутентификации при получении манифестов версий, размещенных на github.com, например для Microsoft Build of OpenJDK. При выполнении этого действия на github.com достаточно значения по умолчанию. При выполнении на GHES вы можете передать личный токен доступа для github.com, если у вас возникают проблемы с ограничением скорости.
 token: # необязательно, по умолчанию ${{ github.server_url == 'https://github.com' && github.token || '' }}
 # Имя идентификатора набора инструментов Maven, если не нужно имя по умолчанию "${distribution}_${java-version}". Примеры поддерживаемого синтаксиса см. в файле «Расширенное использование»
 mvn-toolchain-id: # необязательно
 # Имя поставщика набора инструментов Maven, если не требуется имя по умолчанию "${distribution}". Примеры поддерживаемого синтаксиса см. в файле Advanced Usage
 mvn-toolchain-vendor: # необязательно
 
